from pathlib import Path
from typing import Iterable

from pydantic import ValidationError

from bagel import models


def get_subjects_missing_from_pheno_data(
    subjects: Iterable, pheno_subjects: Iterable
) -> list:
    """Raises informative error if subject IDs exist that are found only in the BIDS directory."""
    return list(set(subjects).difference(pheno_subjects))


def validate_jsonld_against_model(
    jsonld: dict, file_path: Path
) -> models.Dataset:
    """Validate dictionary of user-provided JSONLD against the data model for a dataset."""
    try:
        jsonld_dataset = models.Dataset.parse_obj(jsonld)
    except ValidationError as err:
        raise ValueError(
            f"{file_path} is not a valid Neurobagel JSONLD file. "
            "Please ensure to provide a valid JSONLD file generated by Neurobagel CLI commands.\n"
            f"Validation errors: {str(err)}"
        ) from err

    return jsonld_dataset
